/* Config.hh. Generated by CMake for gz-asv_sim. */

/* Version number */
#define ASV_SIM_MAJOR_VERSION 2
#define ASV_SIM_MINOR_VERSION 0
#define ASV_SIM_PATCH_VERSION 0

#define ASV_SIM_VERSION "2.0"
#define ASV_SIM_VERSION_FULL "2.0.0"
#define ASV_SIM_MAJOR_VERSION_STR "2"

#define ASV_SIM_VERSION_NAMESPACE v2

#define ASV_SIM_VERSION_HEADER "ASV Simulator, version 2.0.0\nCopyright (C) 2022 Rhys Mainwaring.\nReleased under the GPL-3.0 License.\n\n"

#define ASV_SIM_GUI_CONFIG_PATH "/home/pherro/PX4-Autopilot/gz_ws/install/share/gz/asv_sim2/gui"
#define ASV_SIM_SYSTEM_CONFIG_PATH "/home/pherro/PX4-Autopilot/gz_ws/install/share/gz/asv_sim2/systems"
#define ASV_SIM_SERVER_CONFIG_PATH "/home/pherro/PX4-Autopilot/gz_ws/install/share/gz/asv_sim2"
#define ASV_SIM_PLUGIN_INSTALL_DIR "/home/pherro/PX4-Autopilot/gz_ws/install/lib/gz-asv_sim-2/plugins"
#define ASV_SIM_GUI_PLUGIN_INSTALL_DIR "/home/pherro/PX4-Autopilot/gz_ws/install/lib/gz-asv_sim-2/plugins/gui"
#define ASV_SIM_WORLD_INSTALL_DIR "/home/pherro/PX4-Autopilot/gz_ws/install/share/gz/asv_sim2/worlds"

/* #undef ASV_SIM_BUILD_TYPE_PROFILE */
/* #undef ASV_SIM_BUILD_TYPE_DEBUG */
/* #undef ASV_SIM_BUILD_TYPE_RELEASE */
